# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72857e21e091a01a06040306b377f7d9bd566213c0792f621e040f3ef4c0dd3e3d1a69fccd1f6f0a8c066a932e7c92635779be7f08fe0ab25c5b36409134169f

test:
  secret_key_base: dc5942d7b7910dfee6d4c7ab94f10be2b25972c89caf7279ee3c6da43cc261de753023c111eb067988dad81b5ff3548f063fba64c0d982ffc99b41411385cde4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
